name: universal_date_parser
description: A smart, fast, auto-detecting date parser for Dart/Flutter. Supports ISO, slash, dash, text, RFC, and compact formats.
version: 1.0.0
repository: https://github.com/yourusername/universal_date_parser
issue_tracker: https://github.com/yourusername/universal_date_parser/issues


environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  intl: ^0.20.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
